### ISSUE TITLE
Compiled with wrong protocol version

### ISSUE THREAD

**Issue by JamesInform** [PostgresApp/PostgresApp#537] opened 2019-11-17 23:20 UTC
Hi,

when I try to connect to an external PostgreSQL 12 server using the psql (version 12) that comes with the current Postgresapp (Version 2.3.2), I get the following error:

`psql: error: could not connect to server: FATAL:  unsupported frontend protocol 1234.5679: server supports 2.0 to 3.0`

Seems as if something went wrong during your building process.

Best regards,

James

**Comment by jakob** [comment] 2019-11-20 11:39
This is an issue with the server, not the client.

According to [the docs](https://www.postgresql.org/docs/current/protocol-message-formats.html), protocol version `1234.5679` corresponds to an SSLRequest, which would be the first message sent from psql when it tries to open a TLS-encrypted connection.

For some reason, your server does not seem to understand this? You say you are connecting to a PostgreSQL 12 server, but that sounds unlikely. Is there some kind of proxy between you and the server that does not properly support the PostgreSQL connection protocol?

You can probably circumvent the issue by disabling TLS / SSL, but before you do that, make sure you understand the implications of disabling encryption.

**Comment by JamesInform** [comment] 2019-11-20 13:34
Hi Jakob!

Thanks for your response!
There nothing between the client and the server.

The weird thing is, that when I use the psql (version 11.6) client from your Postgresapp, I am able to connect without a problem.

**Comment by jakob** [comment] 2019-11-20 14:15
OK, I still think we need some more info to debug this.

1) What server are you connecting to:
 - how are you connecting to the server (via hostname / IP address / unix socket / SSH Tunnel / ...)
 - exact server version number (eg. from `SELECT VERSION()`)
 - where is the server running? (locally, on a VM, in Docker, hosted PostgreSQL, etc)

2) Can you capture network traffic (eg. with tcpdump: `sudo tcpdump -X -i any port 5432`) and compare the startup process between psql 11.6 and psql 12.1? You don't need to provide correct username / password, the failure happens before authentication.

(you can email dumps to jakob@eggerapps.at if you worry about accidentally disclosing private data)

**Comment by jakob** [comment] 2019-11-20 14:18
Also, the configure string of the server would be very useful, ie. the output of `pg_config --configure` (server side, not client side)

**Comment by JamesInform** [comment] 2019-11-20 23:07
I have built the server myself on Ubuntu 18.04 LTS with all latest updates.

Configure is:
```
pg_config --configure
'--prefix=/opt/pg' '--with-systemd' '--with-icu' '--with-libxml' '--with-libxslt' '--with-perl' '--with-python' '--disable-rpath' '--with-extra-version= MyPostgreSQL' '--with-llvm' '--with-openssl'
```
Ubuntu is running under VMWare Fusion 11.5 on Mac.

I have attached 3 dump files:
- dump1.txt 
Using your psql version 12.1, trying to connect to my server, getting error. 
psql -h 192.168.215.169 -U postgres

- dump2.txt
Using your psql version 12.1, trying to connect to my server, working. 
psql -h 192.168.215.169 -U postgres "sslmode=disable"

- dump3.txt
Using my own psql version 12.1 trying to connect to my server, working. 
psql -h 192.168.215.169 -U postgres

Hope this helps.
[dump1.txt](https://github.com/PostgresApp/PostgresApp/files/3871966/dump1.txt)
[dump2.txt](https://github.com/PostgresApp/PostgresApp/files/3871967/dump2.txt)
[dump3.txt](https://github.com/PostgresApp/PostgresApp/files/3871968/dump3.txt)

**Comment by JamesInform** [comment] 2019-11-20 23:13
Just forgotten:

PostgreSQL 12.1 was built from source pulled from git tag REL_12_1.

https://github.com/postgres/postgres.git

**Comment by jakob** [comment] 2019-12-05 08:12
Sorry for my late reply, I didn't see that you already provided dumps.

I tried to parse your dumps. Here's what's going on:

```
dump1.txt
>
0000 0008 04d2 1630     (GSSAPI auth request)
<                       
4e                      N (not supported)
>                       
0000 0008 04d2 162f     (SSL auth request)
< 
4500 0000 8953 4641 ... (ERROR unsupported frontend protocol)



dump2.txt
>
0000 0008 04d2 1630     (GSSAPI auth request)
<                       
4e                      N (not supported)
>                       
0000 0054 0003 0000 ... Protocol v3 plain text auth request
...



dump3.txt               
>                       
0000 0008 04d2 162f     (SSL Auth Request)
<                       
4e                      N (not supported)
>                       
0000 0054 0003 0000 ... Protocol v3 plain text auth request
...



dump4.txt               
>                       
0000 0008 04d2 162f     (SSL Auth Request)
<                       
4e                      N (not supported)
>                       
0000 0054 0003 0000 ... Protocol v3 plain text auth request
....
```


I don't see any problem from the client side. The server supports neither GSSAPI or SSL, which is fine. Authentication method negotiation seems to work at first, but for some reason the server does not understand the SSL auth request after the GSSAPI request. (But it does respond appropriately if the SSL auth request comes first)

I'm pretty sure this is an issue on the server side.

I'm a bit short on time right now, so I'm not sure I can investigate further. You should probably submit a bug report to PostgreSQL directly, I don't think this has anything to do with Postgres.app

Since you built the PostgreSQL server yourself, could you try building different versions of PostgreSQL so you can find out when the problem first starts happening? Does it occur only with 12.1, or with 12.0 as well? If it's a recent regression, maybe it's already fixed in master?

**Comment by jakob** [comment] 2019-12-05 08:35
OK, I did some more digging. Apparently the server does not support multiple negotiation requests - you can make either a TLS request or a GSS request (see https://github.com/postgres/postgres/blob/9a798234963cd1f746ded41453392c257a4f9fdd/src/backend/postmaster/postmaster.c#L2062)

So I guess the problem is in the client code after all -- it should open a new connection if negotiating GSS failed, before attempting to negotiate TLS. I'm not sure why it does that.

**Comment by JamesInform** [comment] 2019-12-05 23:31
Thanks for your feedback!

So will you take care of further actions and post into the PostgreSQL mailing group if necassary?

**Comment by jakob** [comment] 2019-12-06 13:15
Yes, I'll contact the PostgreSQL mailing list.

I've attempted to patch the problem, but I don't have Kerberos set up, so could you try if the following version of Postgres.app works as expected?

https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/Postgres-2.3.3-12.dmg

**Comment by jakob** [comment] 2019-12-06 13:18
Nevermind, that build is broken. I'll try again.

**Comment by jakob** [comment] 2019-12-06 13:56
This build should work:
https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/Postgres-2.3.3b-12.dmg

**Comment by JamesInform** [comment] 2019-12-06 16:21
Hi Jakob,

thank you very much for your effort.

With your latest build everything works fine!

James

**Comment by jakob** [comment] 2019-12-06 20:20
I'm not sure my client side patch is going to be accepted by the PostgreSQL team, but I assume that the server side issue is going to be fixed.

Andrew Gierth on the mailing list suggested to work around the issue by providing the connection parameter gssencmode=disable

**Comment by jakob** [comment] 2020-01-22 09:19
As discussed in #539, we've stopped building Postgres.app with Kerberos, so this issue should be fixed now!

**Closed by jakob** 2020-01-22 09:19 UTC
