### ISSUE TITLE
Add support for postgis with mvt support

### ISSUE THREAD

**Issue by gerbsen** [PostgresApp/PostgresApp#463] opened 2018-08-29 13:19 UTC
The new PostGIS version supports the [MVT format](https://www.mapbox.com/vector-tiles/specification/) but you need to compile PostGIS with `libprotobuf-c`. Could this be added?

(I'm currently trying to install this with `brew` but somehow this is not picked up the install)

**Comment by mhkeller** [comment] 2018-09-18 04:03
fyi duplicate of https://github.com/PostgresApp/PostgresApp/issues/412

**Comment by jakob** [comment] 2018-09-20 15:13
There's a beta with support for MVT out now! See #412 for details.

Closing this since it is a duplicate.

**Closed by jakob** 2018-09-20 15:13 UTC
