### ISSUE TITLE
gdalwrap shows ERROR 6: Unable to load PROJ.4 library

### ISSUE THREAD

**Issue by zionlion77** [PostgresApp/PostgresApp#208] opened 2014-09-05 21:07 UTC
Hi everyone,

I tried to change the projection of some GeoTiff files with gdalwarp included in PostgresApp 9.3.5.0. 
For convenience, I added export PATH="/Applications/Postgres.app/Contents/Versions/9.3/bin:$PATH" to the bash_profile.
I execute gdalwarp from the terminal on Mac OS X 10.9.4 with the following command:

gdalwarp -s_srs EPSG:4326 -t_srs EPSG:3785 -r bilinear ASTGTM2_N47E007_dem.tif ASTGTM2_N47E007_dem-3785.tif

I get the following error:

ERROR 6: Unable to load PROJ.4 library (libproj.dylib), creation of
OGRCoordinateTransformation failed.
Creating output file that is 3601P x 3601L.
Processing input file ASTGTM2_N47E007_dem.tif.
0...10...20...30...40...50...60...70...80...90...100 - done.

As you can see gdalwarp still writes a file, even after it encountered the error. Therefore, I checked both files (before and after the warp) with gdalinfo and get the following results:

Before (ASTGTM2_N47E007_dem.tif):

Size is 3601, 3601
Coordinate System is:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433],
    AUTHORITY["EPSG","4326"]]
Origin = (6.999861111111112,48.000138888888891)
Pixel Size = (0.000277777777778,-0.000277777777778)
Metadata:
  AREA_OR_POINT=Area
  TIFFTAG_DATETIME=2011:03:16 05:16:57
  TIFFTAG_DOCUMENTNAME=created at
  TIFFTAG_IMAGEDESCRIPTION=SILC TIFF
  TIFFTAG_RESOLUTIONUNIT=2 (pixels/inch)
  TIFFTAG_SOFTWARE=IDL 7.1.1, ITT Visual Information Solutions
  TIFFTAG_XRESOLUTION=100
  TIFFTAG_YRESOLUTION=100
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (   6.9998611,  48.0001389) 
Lower Left  (   6.9998611,  46.9998611) 
Upper Right (   8.0001389,  48.0001389) 
Lower Right (   8.0001389,  46.9998611) 
Center      (   7.5000000,  47.5000000) 
Band 1 Block=3601x1 Type=Int16, ColorInterp=Gray

After (ASTGTM2_N47E007_dem-3785.tif):

Size is 3601, 3601
Coordinate System is:
PROJCS["Popular Visualisation CRS / Mercator",
    GEOGCS["Popular Visualisation CRS",
        DATUM["Popular_Visualisation_Datum",
            SPHEROID["Popular Visualisation Sphere",6378137,0,
                AUTHORITY["EPSG","7059"]],
            TOWGS84[0,0,0,0,0,0,0],
            AUTHORITY["EPSG","6055"]],
        PRIMEM["Greenwich",0],
        UNIT["degree",0.0174532925199433],
        AUTHORITY["EPSG","4055"]],
    PROJECTION["Mercator_1SP"],
    PARAMETER["central_meridian",0],
    PARAMETER["scale_factor",1],
    PARAMETER["false_easting",0],
    PARAMETER["false_northing",0],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    EXTENSION["PROJ4","+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs"],
    AUTHORITY["EPSG","3785"]]
Origin = (6.999861111111112,48.000138888888891)
Pixel Size = (0.000277777777778,-0.000277777777778)
Metadata:
  AREA_OR_POINT=Area
  TIFFTAG_DATETIME=2011:03:16 05:16:57
  TIFFTAG_DOCUMENTNAME=created at
  TIFFTAG_IMAGEDESCRIPTION=SILC TIFF
  TIFFTAG_RESOLUTIONUNIT=2 (pixels/inch)
  TIFFTAG_SOFTWARE=IDL 7.1.1, ITT Visual Information Solutions
  TIFFTAG_XRESOLUTION=100
  TIFFTAG_YRESOLUTION=100
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (   6.9998611,  48.0001389) 
Lower Left  (   6.9998611,  46.9998611) 
Upper Right (   8.0001389,  48.0001389) 
Lower Right (   8.0001389,  46.9998611) 
Center      (   7.5000000,  47.5000000) 
Band 1 Block=3601x1 Type=Int16, ColorInterp=Gray

Since, I am completely new to this field I am not sure, if I can use the converted files or not? Is there a way to fix the PROJ.4 library issue?

Thanks for your help in advance!

cheers,
OSY

**Comment by mattblair** [comment] 2015-04-20 04:09
I ran into the same error trying to use Postgres.app's ogr2ogr to reproject some data with state plane coordinates to WGS84, and based on [this](http://stackoverflow.com/a/13536274), I entered this at the command line in Terminal:

```
export DYLD_FALLBACK_LIBRARY_PATH=$DYLD_FALLBACK_LIBRARY_PATH:/Applications/Postgres.app/Contents/Versions/9.4/lib/
```
And that fixed the error message for ogr2ogr and some other related libraries.

You could also add that to your terminal profile.

**Comment by jakob** [comment] 2016-12-23 10:33
This issue should probably not happen anymore with the most recent versions of Postgres.app, since we've moved to absolute pathnames for dylibs a while ago.

I'm closing this issue now.

If this issue still affects you, please:
- reopen the issue
- provide a command that I can run on my computer to reproduce the issue

(I'm not a geo tools specialist, but I'll try my best to fix this issue if it occurs again.)

**Closed by jakob** 2016-12-23 10:33 UTC
