### ISSUE TITLE
Add a infobox with login credentials and URL

### ISSUE THREAD

**Issue by muescha** [PostgresApp/PostgresApp#355] opened 2016-11-16 19:10 UTC
to fast login to db it would be nice if the welcome screen have an info box with the logincredentials are shown and ready to copy

just now this info is very hidden in the docu at [GUI Tools](http://postgresapp.com/documentation/gui-tools.html)

**Comment by jakob** [comment] 2016-11-20 16:35
This is a duplicate of issue #336

We're planning to redesign the website for Postgres.app 2.0, and this will be a part of it.

**Comment by jakob** [comment] 2016-11-20 16:37
Sorry, I just realised that you are talking about the app, not the website. Reopening...

**Comment by muescha** [comment] 2016-11-24 17:14
Thx

Yes. I mean the Welcome Screen in the App :)

**Comment by jakob** [comment] 2017-03-21 11:44
I've decided not to add an infobox to the app for the following reasons:

- in the new interface there is no good place to put it
- there is now an infobox on the homepage
- this is mostly useful for new users, who probably already have the homepage open anyway

Thanks for taking the time to submit this suggestion -- it was a good point at the time, but for the reasons about I think it's no longer relevant.

**Closed by jakob** 2017-03-21 11:44 UTC
