### ISSUE TITLE
Unable to load PROJ.4 library

### ISSUE THREAD

**Issue by crackernutter** [PostgresApp/PostgresApp#239] opened 2014-12-23 15:38 UTC
After installing Postgres.app 9.4 on MacOS recently, I'm trying to load in some geographic data using ogr2ogr and I get an error when trying to perform a transformation: 

```ERROR 6: Unable to load PROJ.4 library (libproj.dylib), creation of
OGRCoordinateTransformation failed.
Failed to create coordinate transformation between the
following coordinate systems.  This may be because they
are not transformable, or because projection services
(PROJ.4 DLL/.so) could not be loaded.```

I can use --skiperrors but the data doesn't load correctly.
Does anyone know how to fix this - I hesitate to install GDAL over Postgres.app for fear of ruining some dependencies.

**Comment by mattblair** [comment] 2015-04-20 04:03
Regarding temporary work-arounds:

When I tried appending to the DYLD_LIBRARY_PATH (Postgres.app 9.4.1.1 on Yosemite) I got a different error:

```
dyld: Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /Applications/Postgres.app/Contents/Versions/9.4/lib//libjpeg.8.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
Trace/BPT trap: 5
```
However, based on [this](http://stackoverflow.com/a/13536274), I tried:

```
export DYLD_FALLBACK_LIBRARY_PATH=$DYLD_FALLBACK_LIBRARY_PATH:/Applications/Postgres.app/Contents/Versions/9.4/lib/
```

And that fixed the problem with ogr2ogr, and fixed a launch failure I was having with GeoDjango as well.

**Comment by jakob** [comment] 2015-04-28 12:59
I'd like to fix this issue. Can anyone please provide commands to reproduce the issue (with sample data files)?

**Comment by jakob** [comment] 2015-04-28 16:09
Might have fixed this problem in the latest build https://github.com/PostgresApp/PostgresApp/releases/tag/9.4.1.2

**Comment by jakob** [comment] 2015-05-24 10:03
Since I got no more comments, I'm assuming this issue is fixed now. Please reopen if you still run into it using the newest version (currently 9.4.2.0)

**Closed by jakob** 2015-05-24 10:03 UTC

**Comment by wboykinm** [comment] 2015-11-06 17:35
@mattblair thanks for the above - works perfectly.
