### ISSUE TITLE
Downloaded pgAdmin 4 but don't know how to connect PostgresApp to it

### ISSUE THREAD

**Issue by jbains223** [PostgresApp/PostgresApp#442] opened 2018-04-19 18:32 UTC
I downloaded PostgresApp and actually have created a database on it. However, I downloaded pgAdmin today for the graphical client and I don't know how to connect the two. I would like to work on the database from the pgAdmin. 

Also, another issue I'm having is that pgAdmin keeps opening in my browser rather than as a separate application. Is there a way to change this?

Thank you.

**Comment by jbains223** [comment] 2018-04-23 18:37
So I have the Postgres.app as well as pgAdmin4 running on my machine. However, as the pgAdmin uses port 5432 by default, the Postgres.app is telling me that I have to use a different port. However, when I do this, the pgAdmin can not see my database. Is there some way of working around this?

**Comment by jbains223** [comment] 2018-04-23 18:39
So I have the Postgres.app as well as pgAdmin4 running on my machine. However, as the pgAdmin uses port 5432 by default, the Postgres.app is telling me that I have to use a different port. However, when I do this, the pgAdmin can not see my database. Is there some way of working around this?

**Comment by jakob** [comment] 2018-04-23 20:33
Hi @jbains223, you might be mixing something up.

Postgres.app is a server.

pgAdmin4 is a client.

When Postgres.app says "Port in use", that means that some other server is already using this port. The problem is not pgAdmin.

You should probably remove the other server before you start Postgres.app. See this page in the documentation for more info: [Removing existing PostgreSQL Installations ](https://postgresapp.com/documentation/remove.html)

**Comment by jasonchia89** [comment] 2020-04-04 06:47
On a related issue, my Postgres.app (latest version: v12.1) is connected to a different port from that of my pgAdmin4 (v4.2, downloaded together with Postgres v.12.2 from enterprisedb) so that both can run concurrently. When I attempt to create a new server on pgAdmin4 that connects to the port my Postgres.app is set to connect to, I get an error saving that new database on pgAdmin4 that goes like this: FATAL: unsupported frontend protocol 1234.5679: server supports 2.0 to 3.0. Does this mean that the version of the Postgres.app I am using is too advanced for pgAdmin4 to recognize/support (in which case I can simply just download the backward compatible version of Postgres.app and try to update it) or is it the other way around - the latest Postgres.app is too outdated for the latest version of pgAdmin4 in which case there is no solution?

**Comment by jakob** [comment] 2020-05-11 07:28
The `FATAL: unsupported frontend protocol 1234.5679` error sounds very similar to #537. It should be fixed if you download the latest version of Postgres.app. See https://github.com/PostgresApp/PostgresApp/releases for a changelist.

I'm closing this issue now. If you continue experiencing this problem with the latest version of Postgres.app, please open a new issue.

**Closed by jakob** 2020-05-11 07:28 UTC
