### ISSUE TITLE
3.5 asking for password

### ISSUE THREAD

**Issue by decaturrunner** [PostgresApp/PostgresApp#478] opened 2018-11-06 16:46 UTC
I've been using the wonderful PGAdmin for years. Today I updated to 3.5 and could no longer access my local database. It began asking for the postgres user's password, even though the pg_hba.conf file says to allow all local connections. I tried changing the local configuration to use my computer's login user instead of postgres, but again it wanted a password but would not accept my user password or my others that I use for private databases.

I'm using Mac OS 10.14, as I was before upgrading from PGAdmin 3.4 to 3.5. 

I'm still able to log in to remote servers, but just not my local server. Which is a problem because I have some data I need to test before importing it to a production server.

**Comment by jakob** [comment] 2018-11-06 17:20
Did you try a blank password? I recall that PGAdmin always asked for a password even though none was needed.

**Comment by decaturrunner** [comment] 2018-11-06 18:07
Yes, I tried a blank password. But it previously did not ask. And based on pb_hba.conf, it really shouldn't.

**Comment by jakob** [comment] 2018-11-07 07:35
Can you connect with psql?

Also, are you sure that Postgres.app is running on the port you  are trying to connect to? Often these issues are caused by other PostgreSQL installations running on the port you expect. (eg. homebrew)

You can check which PostgreSQL servers are running on your computer using this command:

```bash
ps x | grep postgres
```

A line like this would indicate that Postgres.app is running on port 5432:

```
31287   ??  S      0:00.06 /Applications/Postgres.app/Contents/Versions/11/bin/postgres -D /Users/jakob/Library/Application Support/Postgres/var-11 -p 5432
```

**Comment by decaturrunner** [comment] 2018-11-07 14:06
When I try to connect with psql:

/Applications/Postgres.app/Contents/MacOS/bin/psql


I get:

psql: could not connect to server: No such file or directory

Is the server running locally and accepting

connections on Unix domain socket "/tmp/.s.PGSQL.5432"?


Then I tried:

/Applications/Postgres.app/Contents/MacOS/bin/psql -h 127.0.0.1


and got:

psql: could not connect to server: Connection refused

Is the server running on host "127.0.0.1" and accepting

TCP/IP connections on port 5432?

ps x | grep postgres returned:

 1442 s000  S+     0:00.01 grep postgres



Chuck

**Comment by jakob** [comment] 2018-11-07 14:09
Looks like you don't have a PostgreSQL server running on your Mac.

What happens when you open Postgres.app? Does your server show as running?

**Comment by decaturrunner** [comment] 2018-11-07 14:51
PGAdmin4 asks for the password for postgres, but I don't see any indication that it is running. Except that the Postgres.app menu has "Shut Down Server," suggesting that the app thinks it is running. 
It did not install the way the documentation says it will, as there is no indication of the version in the directory names. In my data directory, PG_VERSION says 9.1. 
One likely relevant fact is that the PGAdmin (3 & 4) "Check for Updates" command has never worked. 
To make sure I have everything, I again downloaded PGAdmin 4 with the Postgres.app (9.5, 9.6, 10, and 11). Then I tried opening Postgres.app. That opens a window that has at the top "PostgreSQL 9.1 ... Binaries not found". That window was not opening before. Looking at the package contents of the Postgres.app, there is a Versions folder with all the versions that should be there. But Postgres.app can't find any of them. Any idea what lets Postgres.app know where to find the binaries?

**Comment by decaturrunner** [comment] 2018-11-07 15:17
When I launch Postgres.app, its process appears in Activity Monitor, which says it has files open including .../Postgres.app/Contents/Versions/11/lib.libpq.5.11.dylib. But running psql from the version 11 bin directory suggests it is not running.

**Comment by jakob** [comment] 2018-11-07 15:23
It looks like you have been using a very old version of Postgres.app, which we don't support any more.

You might be able to get it running installing Postgres.app 9.1.0.0 from here: https://github.com/PostgresApp/PostgresApp/releases/tag/9.1.0.0

Then you can create a dump of your server using pg_dump (see https://postgresapp.com/documentation/migrating-data.html), and upgrade to a newer version.

Do you need to recover data from your old version of Postgres.app? If you don't need any of your old data, I recommend to delete your data directory, delete all copies of Postgres.app, and start with a new version of Postgres.app

**Comment by decaturrunner** [comment] 2018-11-07 15:59
Thanks. I was able to get 9.1 running and succeded with pg_dumpall. But I still can't get any of the new installed versions to start, as Postgres.app still says it can't find the 9.1 binaries.

**Comment by decaturrunner** [comment] 2018-11-07 16:53
I deleted my data directory and all copies of Postgres.app and PGAdmin, emptied the trash, reinstalled Postgres.app and PGAdmin4, and when I started Postgres.app it again says "PostgreSQL 9.1 Binaries not found". pgAdmin still can't connect to the local postgres. There is a Postgres process in the Activity Monitor, but I assume that's the app, not the server.

**Comment by decaturrunner** [comment] 2018-11-07 16:56
Sorry for that last message. Removing everything and starting over did work, once I added to Postgres.app servers for the versions present. Might have worked before if I had realized I had to add a new configuration for each version. Thanks for helping.

**Comment by jakob** [comment] 2018-11-07 17:16
OK. I think we need to make it more clear how to add multiple servers, lots of people stumbling over that.

I'll close this issue, feel free to reopen it if you have further questions!

**Closed by jakob** 2018-11-07 17:16 UTC
