### ISSUE TITLE
Wildfly can't connect

### ISSUE THREAD

**Issue by caarlos0** [PostgresApp/PostgresApp#323] opened 2016-05-20 19:05 UTC
I'm trying to connect to a Postgres.app database through Wildfly Application Server, but I'm getting connection timeouts.

The configuration I tried is:

```xml
<subsystem xmlns="urn:jboss:domain:datasources:3.0">
  <datasources>
      <xa-datasource jndi-name="java:/PostgresXADS" pool-name="PostgresXADS" enabled="true" use-ccm="false">
          <xa-datasource-property name="ServerName">
              localhost
          </xa-datasource-property>
          <xa-datasource-property name="PortNumber">
              5432
          </xa-datasource-property>
          <xa-datasource-property name="DatabaseName">
              test
          </xa-datasource-property>
          <driver>postgresql</driver>
          <security>
              <user-name>carlos</user-name>
          </security>
          <validation>
              <valid-connection-checker class-name="org.jboss.jca.adapters.jdbc.extensions.postgres.PostgreSQLValidConnectionChecker"/>
              <background-validation>true</background-validation>
              <exception-sorter class-name="org.jboss.jca.adapters.jdbc.extensions.postgres.PostgreSQLExceptionSorter"/>
          </validation>
      </xa-datasource>
      <drivers>
          <driver name="postgresql" module="org.postgresql">
              <xa-datasource-class>org.postgresql.xa.PGXADataSource</xa-datasource-class>
          </driver>
      </drivers>
  </datasources>
</subsystem>
```

But I get connection timeouts.

I removed the var folder and restarted Postgres.app, just in case I changed some config and did't remember, but it wasn't the case.

I also tried to connect to another postgresql server, to make sure that it wasn't  the driver itself. That worked, meaning it is probably some issue with Postgres.app and/or my connection setup.

Any tips?

**Comment by jakob** [comment] 2016-05-20 19:13
I'm not familiar with Wildfly, so I can only offer very generic advise.

First, try connecting with psql and see if it works using the same parameters:

    psql -h localhost -p 5432 -U carlos test

Next thing to do would be to check the server log (you can find it inside the data directory).

Connection timeouts are often caused by Firewalls, Internet Filters, Anti-Virus and similar software. If you use anything like that, try uninstalling it and see if the problem persists.

**Comment by caarlos0** [comment] 2016-05-20 19:16
I forgot to mention that, connecting with other clients work (psql, go client, rails, pgadmin, etc)..

**Comment by caarlos0** [comment] 2016-05-20 19:21
Disabling the OSX firewall didn't work.

FWIW, the connection keeps in `SYN_SENT` state:

```
java     43423 carlos  386u  IPv4 0x9bbb9382819712eb      0t0  TCP localhost:52594->localhost:postgresql (SYN_SENT)
```

**Comment by caarlos0** [comment] 2016-05-20 19:50
Found it!

I had an entry in my `/etc/hosts

**Comment by jakob** [comment] 2016-06-20 11:35
Maybe the PostgreSQL server was listening on 127.0.1.1 and Wildfly was trying to connect to 127.0.0.1 (or the other way around). They are both loopback addresses, but they are not the same.

I'm closing this issue now.

**Closed by jakob** 2016-06-20 11:35 UTC

**Comment by caarlos0** [comment] 2016-06-20 12:10
@jakob yeah, kind of weird though... 

anyways, thanks
