### ISSUE TITLE
Please Update Postgresapp / PLV8 and Python3

### ISSUE THREAD

**Issue by JamesInform** [PostgresApp/PostgresApp#549] opened 2020-01-21 23:28 UTC
Hi,

it would be fine, if you could update the Postgresapp:

1. Meanwhile PLV8 2.3.14 is available which fixes a severe bug with
`set plv8.start_proc = 'plv8_init';`

2. Python2 has reached end of life on the 1st of January 2020. Please also include the plpython3u extension into Postgrespp.

James

**Comment by jakob** [comment] 2020-01-22 08:47
We usually update Postgres.app whenever a new version of PostgreSQL is released. The next PostgreSQL maintenance release is scheduled for Thursday, February 13. It usually takes me a full day to make new builds of Postgres.app, so I only do additional updates when severe bugs occur.

After quick googling I didn't find any discussion of the plv8 issue, so it's hard for me to assess the impact / severity. Could you provide a link to more details?

As for Python 3, that's a separate issue, and I don't have a quick and easy answer. I've create issue #551 to discuss the move to Python 3. Input is appreciated!

**Comment by JamesInform** [comment] 2020-01-22 20:13
Could it be this commit?

[Allocate FunctionCallInfo on the stack.](https://github.com/plv8/plv8/commit/af456b491cc26766d2ace7faf8677dac4ae4972c)

This is backmerged into 2.3.14

**Comment by jakob** [comment] 2020-01-22 20:22
I've read the commit message and the issue linked in the commit message and I still don't understand the impact of the bug. What doesn't work in the old version of plv8?

**Comment by tbussmann** [comment] 2020-01-22 22:10
There seems to be a crashing bug in the [`plv8.find_function`](https://plv8.github.io/#-code-plv8-find_function-code-) affecting PostgreSQL 12 with plv8. It seems to be fixed by https://github.com/plv8/plv8/pull/375 for 2.3.14
I can reproduce it with the current build containing 2.3.13 where plv8 does work for simple cases. I can't estimate how likely users are hit in real world scenarios either, but as I understood the docs this method is necessary to call other plv8 functions from within plv8 functions, so this seems to be quite common.

**Comment by JamesInform** [comment] 2020-01-22 22:30
The error directly occurs if you use the recommended Startup-Procedure to initialize e.g. a PLV8 library. 

It's been described on the first page of the plv8 documentation:
[https://plv8.github.io/#start-up-procedure](https://plv8.github.io/#start-up-procedure)

So, if one is seriously using plv8 (which I am doing) then you directly run into this issue.

**Comment by tbussmann** [comment] 2020-01-23 01:11
I can confirm the issue is no longer reproducible in a testbuild with plv8 2.3.14

**Comment by jakob** [comment] 2020-01-23 07:48
OK. Thanks. That's a good reason to update. I'll start the builds...

**Comment by JamesInform** [comment] 2020-01-23 08:46
Great. Thanks!

**Comment by jakob** [comment] 2020-01-24 15:53
Hey! I made a new build. It took us a bit of time to get the new hardened runtime stuff sorted out, but I think it should work now.

Can you verify that this build works before we release it?
https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/Postgres-2.3.3e-12.dmg

**Comment by jakob** [comment] 2020-01-25 11:54
OK, I just released a new build of Postgres.app  (2.3.3e) with the plv8 fix. As far as my limited testing goes, it seems to work now. Please re-open this issue if the problem persists!

Thanks a lot for taking the time to report and follow up on this issue!

**Closed by jakob** 2020-01-25 11:54 UTC
