### ISSUE TITLE
macOS Sonoma Critical Problems

### ISSUE THREAD

**Issue by MattOates** [PostgresApp/PostgresApp#721] opened 2023-06-30 19:09 UTC
When clicking the app icon in the menubar the PgApp menu doesn't show after a delay in freezing all input to the laptop. Then mouse is returned but the keyboard is kept in an extremely broken state. Almost all keyboard content is stuck on some off screen focus causing system bell when anything is typed. Using the mouse other UI elements can be given focus but all keyboards external and built in are stuck in some off screen input that doesn't accept typing. Things like cmd+tab work. I've submitted this to Apple's feedback. But the reality is its very specifically and reproducibly a problem with the PostgresApp menu. I've not found anything else that triggers this behaviour. A user has to completely reboot their machine to get back keyboard input, so I would either warn people of this or take a look.

**Comment by MattOates** [comment] 2023-06-30 19:16
Just checked, force killing just the PG Menu Helper app running in the background will also return keyboard input.

**Comment by jakob** [comment] 2023-07-01 04:21
I'll check if there's anything we can do, but unfortunately bugs like this are common with early macOS betas.

Could you please let us know what version of macOS and Postgres.app you are having issues with?

Are you running macOS Sonoma in a VM or on a real Mac?

Did you update your Mac to macOS Sonoma, with Postgres.app already installed? Or did you install Postgres.app after installing Sonoma?

**Comment by t40mas** [comment] 2023-07-01 05:22
I can confirm this behavior.

Latest Version: v2.6.4
MacBook Pro 16 2021
MacOs 14.0 Beta (23A5276g)

It might be the same issue that plagued the maccy project.
https://github.com/p0deje/Maccy/issues/566

**Comment by jakob** [comment] 2023-07-01 10:09
I've tried to reproduce the issue on my test VM (macOS Sonoma 23A5257q, I think that's Beta 1, running in UTM) with Postgres.app 2.6.4, and it works as expected. So it seems this is  something they broke in Sonoma Beta 2.

Since the issue you linked mentions a total of 4 other affected apps, I think it's safe to assume this is nothing specific to Postgres.app.

If you want to continue debugging the issue, the next step would be to sample the stuck process with Activity Monitor, to see where exactly it is hanging.

But I think at this point the best course of action is if everyone affected reports the problem with Feedback Assistant and we hope for Apple to fix the issue in Beta 3.

Meanwhile, I'll try to figure out how to update my VM to Beta 2, because System Settings says "no updates available".

**Comment by jakob** [comment] 2023-07-02 16:08
OK, so I've now done some testing on Sonoma Beta 2 / 23A5276g (had to create a new VM from scratch).

I can confirm the issue. Clicking the menu bar icon doesn't do anything, and breaks keyboard input. Killing the app fixes the issue.

I tried looking at stack traces in Activity Monitor. Everything looks fine from the perspective of PostgresMenuHelper. The only odd thing is that clicking the icon again shows a message that a menu is being updated that is already on screen. So it seems that from the perspective of PostgresMenuHelper, the menu is already displayed.

So my assumption is that this is some kind of bug in WindowServer. This would also explain why keyboard input doesn't work even when switching apps. If WindowServer worked correctly, then activating another app should send keyboard input to that app.

Anyway, at this point I'm giving up. Thanks for reporting it. I'll check it if it's still broken in Beta 3, but for now there's nothing I can do.

**Comment by cfigueiroa** [comment] 2023-07-05 12:27
> OK, so I've now done some testing on Sonoma Beta 2 / 23A5276g (had to create a new VM from scratch).
> 
> I can confirm the issue. Clicking the menu bar icon doesn't do anything, and breaks keyboard input. Killing the app fixes the issue.
> 
> I tried looking at stack traces in Activity Monitor. Everything looks fine from the perspective of PostgresMenuHelper. The only odd thing is that clicking the icon again shows a message that a menu is being updated that is already on screen. So it seems that from the perspective of PostgresMenuHelper, the menu is already displayed.
> 
> So my assumption is that this is some kind of bug in WindowServer. This would also explain why keyboard input doesn't work even when switching apps. If WindowServer worked correctly, then activating another app should send keyboard input to that app.
> 
> Anyway, at this point I'm giving up. Thanks for reporting it. I'll check it if it's still broken in Beta 3, but for now there's nothing I can do.

While i'm suffering from the same issue i totally understand the decision for not looking at this atm due being a beta OS.

As a workaround, theres anyway to disable the application from launching the status menu icon?

**Comment by jakob** [comment] 2023-07-05 14:22
> [is] there any way to disable the PostgresMenuHelper from starting with Postgres.app?

Yes. Open Postgres.app, select "Settings" from the "Postgres" menu, then uncheck "Show Postgres in menu bar".

**Comment by t40mas** [comment] 2023-07-05 20:12
Beta 3 fixed that issue  🎉

**Comment by gokomer** [comment] 2023-07-05 22:47
I can confirm it is fixed in Beta 3

**Comment by jakob** [comment] 2023-07-06 09:16
@t40mas @gokomer Thanks for letting us know! I'll leave the issue open for a few days so people who are still on Beta 2 can find it more easily, and close it then.

**Comment by MattOates** [comment] 2023-07-06 12:49
Just updated to Beta 3, fixed for me too (false alarm)

**Comment by MattOates** [comment] 2023-07-06 12:51
> I'll check if there's anything we can do, but unfortunately bugs like this are common with early macOS betas.
> 
> Could you please let us know what version of macOS and Postgres.app you are having issues with?
> 
> Are you running macOS Sonoma in a VM or on a real Mac?
> 
> Did you update your Mac to macOS Sonoma, with Postgres.app already installed? Or did you install Postgres.app after installing Sonoma?

Sorry this was Sonoma Beta 2 on hardware, and the version 2.6.4 (198) of the app.

**Comment by jakob** [comment] 2023-07-06 12:53
@MattOates no problem, we were able to figure it out :) Thanks a lot for reporting the issue! It could have just as well been an issue with Postgres.app

**Closed** 2023-07-19 09:47 UTC
